"""CMake toolchain management for STM32 projects."""

from pathlib import Path
from dataclasses import dataclass


@dataclass
class ToolchainConfig:
    """STM32 toolchain configuration for CMake."""

    toolchain: str  # gcc / armclang
    prefix: str  # cross-compiler prefix
    cpu_flags: str  # -mcpu=... flags
    fpu_flags: str  # floating-point flags
    float_abi: str  # ABI for floats


# Known compiler configurations
TOOLCHAIN_CONFIGS: dict[str, ToolchainConfig] = {
    "gcc": ToolchainConfig(
        toolchain="gcc",
        prefix="arm-none-eabi-",
        cpu_flags="",  # Determined per chip
        fpu_flags="",
        float_abi="",
    ),
    "armclang": ToolchainConfig(
        toolchain="armclang",
        prefix="armclang",
        cpu_flags="",
        fpu_flags="",
        float_abi="",
    ),
}


# CPU flags per Cortex variant
CORTEX_FLAGS: dict[str, str] = {
    "M0": "-mcpu=cortex-m0",
    "M0PLUS": "-mcpu=cortex-m0plus",
    "M1": "-mcpu=cortex-m1",
    "M3": "-mcpu=cortex-m3",
    "M4": "-mcpu=cortex-m4",
    "M7": "-mcpu=cortex-m7",
    "M23": "-mcpu=cortex-m23",
    "M33": "-mcpu=cortex-m33",
}

# Series to Cortex mapping
SERIES_CORTEX: dict[str, str] = {
    "G0": "M0PLUS",
    "F0": "M0",
    "F1": "M3",
    "F2": "M3",
    "F3": "M4",
    "F4": "M4",
    "F7": "M7",
    "H7": "M7",
    "L0": "M0PLUS",
    "L1": "M3",
    "L4": "M4",
    "G4": "M4",
    "WB": "M4",
    "WL": "M4",
}


def get_cortex_variant(chip_series: str) -> str:
    """Get Cortex-M variant for a chip series.

    Args:
        chip_series: STM32 series (G0, F4, H7, etc.)

    Returns:
        Cortex-M variant (M0PLUS, M4, M7, etc.)
    """
    return SERIES_CORTEX.get(chip_series.upper(), "M4")


def get_cpu_flags(chip_series: str) -> str:
    """Get CPU compile flags for a chip series.

    Args:
        chip_series: STM32 series (G0, F4, etc.)

    Returns:
        GCC CPU flags string
    """
    cortex = get_cortex_variant(chip_series)
    return CORTEX_FLAGS.get(cortex, "-mcpu=cortex-m4")


def generate_toolchain_content(
    chip_series: str,
    linker_script: str | None = None,
    toolchain: str = "gcc",
) -> str:
    """Generate toolchain.cmake content for an STM32 project.

    Args:
        chip_series: STM32 series identifier (G0, F4, etc.)
        linker_script: Path or name of the linker script (.ld)
        toolchain: Toolchain type (gcc / armclang)

    Returns:
        CMake toolchain file content as string
    """
    tc = TOOLCHAIN_CONFIGS.get(toolchain, TOOLCHAIN_CONFIGS["gcc"])
    cpu_flags = get_cpu_flags(chip_series)

    lines = [
        "# STM32 CMake Toolchain - Generated by LingChain MCP",
        f"# Target: STM32{chip_series} / {toolchain}",
        "",
        "set(CMAKE_SYSTEM_NAME               Generic)",
        "set(CMAKE_SYSTEM_PROCESSOR          arm)",
        "",
        f"set(TOOLCHAIN_PREFIX                {tc.prefix})",
        "",
        f"set(CMAKE_C_COMPILER                ${{TOOLCHAIN_PREFIX}}gcc)",
        f"set(CMAKE_ASM_COMPILER              ${{CMAKE_C_COMPILER}})",
        f"set(CMAKE_CXX_COMPILER              ${{TOOLCHAIN_PREFIX}}g++)",
        f"set(CMAKE_LINKER                    ${{TOOLCHAIN_PREFIX}}g++)",
        f"set(CMAKE_OBJCOPY                   ${{TOOLCHAIN_PREFIX}}objcopy)",
        f"set(CMAKE_SIZE                      ${{TOOLCHAIN_PREFIX}}size)",
        "",
        "set(CMAKE_EXECUTABLE_SUFFIX_ASM     \".elf\")",
        "set(CMAKE_EXECUTABLE_SUFFIX_C       \".elf\")",
        "set(CMAKE_EXECUTABLE_SUFFIX_CXX     \".elf\")",
        "",
        "set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)",
        "",
        "# MCU specific flags",
        f"set(TARGET_FLAGS \"{cpu_flags}\")",
        "",
        "set(CMAKE_C_FLAGS \"${CMAKE_C_FLAGS} ${TARGET_FLAGS}\")",
        "set(CMAKE_ASM_FLAGS \"${CMAKE_C_FLAGS} -x assembler-with-cpp -MMD -MP\")",
        "set(CMAKE_C_FLAGS \"${CMAKE_C_FLAGS} -Wall -fdata-sections -ffunction-sections\")",
        "",
        "set(CMAKE_C_FLAGS_DEBUG \"-O0 -g3\")",
        "set(CMAKE_C_FLAGS_RELEASE \"-Os -g0\")",
        "set(CMAKE_CXX_FLAGS_DEBUG \"-O0 -g3\")",
        "set(CMAKE_CXX_FLAGS_RELEASE \"-Os -g0\")",
        "",
        "set(CMAKE_CXX_FLAGS \"${CMAKE_C_FLAGS} -fno-rtti -fno-exceptions -fno-threadsafe-statics\")",
        "",
    ]

    # Linker flags with optional linker script
    linker_script_line = ""
    if linker_script:
        linker_script_line = f" -T \"${{CMAKE_SOURCE_DIR}}/{linker_script}\""

    lines.extend([
        "set(CMAKE_EXE_LINKER_FLAGS \"${TARGET_FLAGS}\")",
        f"set(CMAKE_EXE_LINKER_FLAGS \"${{CMAKE_EXE_LINKER_FLAGS}}{linker_script_line}\")",
        "set(CMAKE_EXE_LINKER_FLAGS \"${CMAKE_EXE_LINKER_FLAGS} --specs=nano.specs\")",
        "set(CMAKE_EXE_LINKER_FLAGS \"${CMAKE_EXE_LINKER_FLAGS} -Wl,-Map=${CMAKE_PROJECT_NAME}.map -Wl,--gc-sections\")",
        "set(CMAKE_EXE_LINKER_FLAGS \"${CMAKE_EXE_LINKER_FLAGS} -Wl,--print-memory-usage\")",
        "set(TOOLCHAIN_LINK_LIBRARIES \"m\")",
    ])

    return "\n".join(lines) + "\n"
